# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-ast
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.8
        args: [--target-version, py38, deczoo, tests]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [--skip, "B101,B403", --recursive, deczoo, tests]
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args: [-vv, --ignore-module, --ignore-init-method, --ignore-private, --ignore-magic, --ignore-nested-functions, --fail-under=80, deczoo]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: 7638d0035a770dd67283b7d464e4db3c0043f609
    hooks:
    -   id: python-no-eval
