site_name: deczoo
repo_url: https://github.com/FBruzzesi/deczoo
site_url: https://fbruzzesi.github.io/deczoo/
site_description: Deczoo - A zoo for decorators
site_author: Francesco Bruzzesi

nav:
  - Home: index.md
  # - Getting Started:
  #   - Quickstart: quickstart/index.md
  #   - FAQ: quickstart/faq.md
  - Examples:
    - Usage: examples.md
  - API:
    - decorators: api/decorators.md
plugins:
  - search
  - mkdocstrings
theme:
  name: material
  # favicon: icon.png
  # logo: icon.png
  font:
    text: Ubuntu
    code: Ubuntu Mono
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
