name: Python Code Checks

on:
  pull_request:
    branches:
    - main

jobs:

  interrogate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --no-cache-dir
          python -m pip install interrogate==1.5.0 --no-cache-dir
      - name: Interrogate
        run: interrogate -vv --ignore-nested-functions --ignore-module --ignore-init-method --ignore-private --ignore-magic --ignore-property-decorators --fail-under=90 deczoo tests

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    needs: [interrogate]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --no-cache-dir
          python -m pip install pytest==7.2.0 --no-cache-dir
          python -m pip install . --no-cache-dir
      - name: Test
        run: pytest tests -vv

  style:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black==22.12.0 isort==5.10.1 --no-cache-dir
      - name: Sort
        run: isort -l 90 .
      - name: Format
        run: black --target-version py310 --line-length 90 deczoo tests
