name: Pre-commit auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Every 1st of the month at 00:00 UTC

permissions: write-all

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: pre-commit install autoupdate
        run: |
          pip install pre-commit
          pre-commit autoupdate

      - name: Commit and push changes
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-pre-commit-hooks
          title: 'Update pre-commit hooks'
          commit-message: 'Update pre-commit hooks'
          body: |
              Update versions of pre-commit hooks to latest versions.
